/**
 * Emoji Metadata & GitHub Shortcode Standards
 *
 * Provides:
 * - GitHub :emoji: shortcode mappings
 * - Mono/Color pairing information
 * - Size adjustment hints for proper rendering
 * - Category groupings
 */

export interface EmojiMetadata {
  code: number;
  char: string;
  githubShortcode: string;
  category: EmojiCategory;
  sizeHint?: number; // Scale factor (0.5-2.0, default 1.0)
  description: string;
  hasMonoVersion: boolean;
  hasColorVersion: boolean;
}

export type EmojiCategory =
  | "faces-smiling"
  | "faces-affection"
  | "faces-negative"
  | "faces-neutral"
  | "gestures"
  | "hearts"
  | "symbols-basic"
  | "symbols-arrows"
  | "symbols-shapes"
  | "weather"
  | "nature-animals"
  | "nature-plants"
  | "food-fruit"
  | "food-prepared"
  | "objects-tech"
  | "objects-tools"
  | "objects-other"
  | "media-controls"
  | "misc";

/**
 * Core Emoji Set with GitHub Shortcodes
 * Matched pairs available in both mono and color
 */
export const EMOJI_CORE: EmojiMetadata[] = [
  // === FACES - SMILING ===
  {
    code: 0x1f600,
    char: "😀",
    githubShortcode: "grinning",
    category: "faces-smiling",
    description: "Grinning face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f603,
    char: "😃",
    githubShortcode: "smiley",
    category: "faces-smiling",
    description: "Grinning face with big eyes",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f604,
    char: "😄",
    githubShortcode: "smile",
    category: "faces-smiling",
    description: "Grinning face with smiling eyes",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f601,
    char: "😁",
    githubShortcode: "grin",
    category: "faces-smiling",
    description: "Beaming face with smiling eyes",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f606,
    char: "😆",
    githubShortcode: "laughing",
    category: "faces-smiling",
    description: "Grinning squinting face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f60a,
    char: "😊",
    githubShortcode: "blush",
    category: "faces-smiling",
    description: "Smiling face with smiling eyes",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f609,
    char: "😉",
    githubShortcode: "wink",
    category: "faces-smiling",
    description: "Winking face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },

  // === FACES - AFFECTION ===
  {
    code: 0x1f60d,
    char: "😍",
    githubShortcode: "heart_eyes",
    category: "faces-affection",
    description: "Smiling face with heart-eyes",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f618,
    char: "😘",
    githubShortcode: "kissing_heart",
    category: "faces-affection",
    description: "Face blowing a kiss",
    hasMonoVersion: false,
    hasColorVersion: true,
  },
  {
    code: 0x1f61c,
    char: "😜",
    githubShortcode: "stuck_out_tongue_winking_eye",
    category: "faces-affection",
    description: "Winking face with tongue",
    hasMonoVersion: true,
    hasColorVersion: true,
  },

  // === FACES - NEUTRAL/NEGATIVE ===
  {
    code: 0x1f610,
    char: "😐",
    githubShortcode: "neutral_face",
    category: "faces-neutral",
    description: "Neutral face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f611,
    char: "😑",
    githubShortcode: "expressionless",
    category: "faces-neutral",
    description: "Expressionless face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f60f,
    char: "😏",
    githubShortcode: "smirk",
    category: "faces-neutral",
    description: "Smirking face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f612,
    char: "😒",
    githubShortcode: "unamused",
    category: "faces-neutral",
    description: "Unamused face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f614,
    char: "😔",
    githubShortcode: "pensive",
    category: "faces-negative",
    description: "Pensive face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f622,
    char: "😢",
    githubShortcode: "cry",
    category: "faces-negative",
    description: "Crying face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f621,
    char: "😡",
    githubShortcode: "rage",
    category: "faces-negative",
    description: "Pouting face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f620,
    char: "😠",
    githubShortcode: "angry",
    category: "faces-negative",
    description: "Angry face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },

  // === SPECIAL ===
  {
    code: 0x1f480,
    char: "💀",
    githubShortcode: "skull",
    category: "faces-negative",
    description: "Skull",
    hasMonoVersion: true,
    hasColorVersion: true,
  },

  // === GESTURES & HANDS ===
  {
    code: 0x1f44d,
    char: "👍",
    githubShortcode: "+1",
    category: "gestures",
    description: "Thumbs up",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f44e,
    char: "👎",
    githubShortcode: "-1",
    category: "gestures",
    description: "Thumbs down",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f44a,
    char: "👊",
    githubShortcode: "facepunch",
    category: "gestures",
    description: "Oncoming fist",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x270a,
    char: "✊",
    githubShortcode: "fist",
    category: "gestures",
    description: "Raised fist",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f44f,
    char: "👏",
    githubShortcode: "clap",
    category: "gestures",
    description: "Clapping hands",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f64f,
    char: "🙏",
    githubShortcode: "pray",
    category: "gestures",
    description: "Folded hands",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f44b,
    char: "👋",
    githubShortcode: "wave",
    category: "gestures",
    description: "Waving hand",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x270b,
    char: "✋",
    githubShortcode: "hand",
    category: "gestures",
    description: "Raised hand",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f44c,
    char: "👌",
    githubShortcode: "ok_hand",
    category: "gestures",
    description: "OK hand",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x270c,
    char: "✌",
    githubShortcode: "v",
    category: "gestures",
    description: "Victory hand",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f448,
    char: "👈",
    githubShortcode: "point_left",
    category: "gestures",
    description: "Backhand pointing left",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f449,
    char: "👉",
    githubShortcode: "point_right",
    category: "gestures",
    description: "Backhand pointing right",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f446,
    char: "👆",
    githubShortcode: "point_up_2",
    category: "gestures",
    description: "Backhand pointing up",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f447,
    char: "👇",
    githubShortcode: "point_down",
    category: "gestures",
    description: "Backhand pointing down",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x261d,
    char: "☝",
    githubShortcode: "point_up",
    category: "gestures",
    description: "Index pointing up",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4aa,
    char: "💪",
    githubShortcode: "muscle",
    category: "gestures",
    description: "Flexed biceps",
    hasMonoVersion: true,
    hasColorVersion: true,
  },

  // === HEARTS ===
  {
    code: 0x2764,
    char: "❤",
    githubShortcode: "heart",
    category: "hearts",
    description: "Red heart",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.9,
  },
  {
    code: 0x1f494,
    char: "💔",
    githubShortcode: "broken_heart",
    category: "hearts",
    description: "Broken heart",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.9,
  },
  {
    code: 0x1f495,
    char: "💕",
    githubShortcode: "two_hearts",
    category: "hearts",
    description: "Two hearts",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.85,
  },
  {
    code: 0x1f496,
    char: "💖",
    githubShortcode: "sparkling_heart",
    category: "hearts",
    description: "Sparkling heart",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.9,
  },
  {
    code: 0x1f497,
    char: "💗",
    githubShortcode: "heartpulse",
    category: "hearts",
    description: "Growing heart",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.9,
  },
  {
    code: 0x1f498,
    char: "💘",
    githubShortcode: "cupid",
    category: "hearts",
    description: "Heart with arrow",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.9,
  },
  {
    code: 0x2665,
    char: "♥",
    githubShortcode: "hearts",
    category: "hearts",
    description: "Heart suit",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.85,
  },

  // === STARS & SPARKLES ===
  {
    code: 0x2b50,
    char: "⭐",
    githubShortcode: "star",
    category: "symbols-shapes",
    description: "Star",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f31f,
    char: "🌟",
    githubShortcode: "star2",
    category: "symbols-shapes",
    description: "Glowing star",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x2728,
    char: "✨",
    githubShortcode: "sparkles",
    category: "symbols-shapes",
    description: "Sparkles",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.85,
  },
  {
    code: 0x1f4ab,
    char: "💫",
    githubShortcode: "dizzy",
    category: "symbols-shapes",
    description: "Dizzy",
    hasMonoVersion: true,
    hasColorVersion: true,
  },

  // === WEATHER ===
  {
    code: 0x2600,
    char: "☀",
    githubShortcode: "sunny",
    category: "weather",
    description: "Sun",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x26c5,
    char: "⛅",
    githubShortcode: "partly_sunny",
    category: "weather",
    description: "Sun behind cloud",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x2601,
    char: "☁",
    githubShortcode: "cloud",
    category: "weather",
    description: "Cloud",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x2744,
    char: "❄",
    githubShortcode: "snowflake",
    category: "weather",
    description: "Snowflake",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.85,
  },
  {
    code: 0x1f319,
    char: "🌙",
    githubShortcode: "crescent_moon",
    category: "weather",
    description: "Crescent moon",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f31d,
    char: "🌝",
    githubShortcode: "full_moon_with_face",
    category: "weather",
    description: "Full moon face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f31b,
    char: "🌛",
    githubShortcode: "first_quarter_moon_with_face",
    category: "weather",
    description: "First quarter moon face",
    hasMonoVersion: true,
    hasColorVersion: true,
  },

  // === SYMBOLS - BASIC ===
  {
    code: 0x2705,
    char: "✅",
    githubShortcode: "white_check_mark",
    category: "symbols-basic",
    description: "Check mark button",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x274c,
    char: "❌",
    githubShortcode: "x",
    category: "symbols-basic",
    description: "Cross mark",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x2795,
    char: "➕",
    githubShortcode: "heavy_plus_sign",
    category: "symbols-basic",
    description: "Plus",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x2796,
    char: "➖",
    githubShortcode: "heavy_minus_sign",
    category: "symbols-basic",
    description: "Minus",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x2716,
    char: "✖",
    githubShortcode: "heavy_multiplication_x",
    category: "symbols-basic",
    description: "Multiplication",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x2797,
    char: "➗",
    githubShortcode: "heavy_division_sign",
    category: "symbols-basic",
    description: "Division",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x2757,
    char: "❗",
    githubShortcode: "exclamation",
    category: "symbols-basic",
    description: "Exclamation mark",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x2753,
    char: "❓",
    githubShortcode: "question",
    category: "symbols-basic",
    description: "Question mark",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x26a0,
    char: "⚠",
    githubShortcode: "warning",
    category: "symbols-basic",
    description: "Warning",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f6ab,
    char: "🚫",
    githubShortcode: "no_entry_sign",
    category: "symbols-basic",
    description: "Prohibited",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f525,
    char: "🔥",
    githubShortcode: "fire",
    category: "symbols-basic",
    description: "Fire",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4a5,
    char: "💥",
    githubShortcode: "boom",
    category: "symbols-basic",
    description: "Collision",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x2139,
    char: "ℹ",
    githubShortcode: "information_source",
    category: "symbols-basic",
    description: "Information",
    hasMonoVersion: true,
    hasColorVersion: true,
  },

  // === ARROWS ===
  {
    code: 0x2b06,
    char: "⬆",
    githubShortcode: "arrow_up",
    category: "symbols-arrows",
    description: "Up arrow",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x27a1,
    char: "➡",
    githubShortcode: "arrow_right",
    category: "symbols-arrows",
    description: "Right arrow",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x2b07,
    char: "⬇",
    githubShortcode: "arrow_down",
    category: "symbols-arrows",
    description: "Down arrow",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x2b05,
    char: "⬅",
    githubShortcode: "arrow_left",
    category: "symbols-arrows",
    description: "Left arrow",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x2194,
    char: "↔",
    githubShortcode: "left_right_arrow",
    category: "symbols-arrows",
    description: "Left-right arrow",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.75,
  },
  {
    code: 0x2195,
    char: "↕",
    githubShortcode: "arrow_up_down",
    category: "symbols-arrows",
    description: "Up-down arrow",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.75,
  },
  {
    code: 0x21a9,
    char: "↩",
    githubShortcode: "leftwards_arrow_with_hook",
    category: "symbols-arrows",
    description: "Right arrow curving left",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x21aa,
    char: "↪",
    githubShortcode: "arrow_right_hook",
    category: "symbols-arrows",
    description: "Left arrow curving right",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },

  // === MEDIA CONTROLS ===
  {
    code: 0x25b6,
    char: "▶",
    githubShortcode: "arrow_forward",
    category: "media-controls",
    description: "Play",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x23f8,
    char: "⏸",
    githubShortcode: "pause_button",
    category: "media-controls",
    description: "Pause",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x23f9,
    char: "⏹",
    githubShortcode: "stop_button",
    category: "media-controls",
    description: "Stop",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x23fa,
    char: "⏺",
    githubShortcode: "record_button",
    category: "media-controls",
    description: "Record",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x23ed,
    char: "⏭",
    githubShortcode: "next_track_button",
    category: "media-controls",
    description: "Next track",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x23ee,
    char: "⏮",
    githubShortcode: "previous_track_button",
    category: "media-controls",
    description: "Previous track",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x23e9,
    char: "⏩",
    githubShortcode: "fast_forward",
    category: "media-controls",
    description: "Fast forward",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x23ea,
    char: "⏪",
    githubShortcode: "rewind",
    category: "media-controls",
    description: "Rewind",
    hasMonoVersion: true,
    hasColorVersion: true,
    sizeHint: 0.8,
  },
  {
    code: 0x1f509,
    char: "🔉",
    githubShortcode: "sound",
    category: "media-controls",
    description: "Speaker medium volume",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f50a,
    char: "🔊",
    githubShortcode: "loud_sound",
    category: "media-controls",
    description: "Speaker high volume",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f507,
    char: "🔇",
    githubShortcode: "mute",
    category: "media-controls",
    description: "Muted speaker",
    hasMonoVersion: true,
    hasColorVersion: true,
  },

  // === OBJECTS - TECH ===
  {
    code: 0x1f4a1,
    char: "💡",
    githubShortcode: "bulb",
    category: "objects-tech",
    description: "Light bulb",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f50d,
    char: "🔍",
    githubShortcode: "mag",
    category: "objects-tech",
    description: "Magnifying glass",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f511,
    char: "🔑",
    githubShortcode: "key",
    category: "objects-tech",
    description: "Key",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f512,
    char: "🔒",
    githubShortcode: "lock",
    category: "objects-tech",
    description: "Locked",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f513,
    char: "🔓",
    githubShortcode: "unlock",
    category: "objects-tech",
    description: "Unlocked",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4be,
    char: "💾",
    githubShortcode: "floppy_disk",
    category: "objects-tech",
    description: "Floppy disk",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4bb,
    char: "💻",
    githubShortcode: "computer",
    category: "objects-tech",
    description: "Laptop",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x2328,
    char: "⌨",
    githubShortcode: "keyboard",
    category: "objects-tech",
    description: "Keyboard",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4f1,
    char: "📱",
    githubShortcode: "iphone",
    category: "objects-tech",
    description: "Mobile phone",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4de,
    char: "📞",
    githubShortcode: "telephone_receiver",
    category: "objects-tech",
    description: "Telephone",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4e7,
    char: "📧",
    githubShortcode: "e-mail",
    category: "objects-tech",
    description: "E-mail",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4c1,
    char: "📁",
    githubShortcode: "file_folder",
    category: "objects-tech",
    description: "File folder",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4c2,
    char: "📂",
    githubShortcode: "open_file_folder",
    category: "objects-tech",
    description: "Open file folder",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4dd,
    char: "📝",
    githubShortcode: "memo",
    category: "objects-tech",
    description: "Memo",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x270f,
    char: "✏",
    githubShortcode: "pencil2",
    category: "objects-tools",
    description: "Pencil",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4cc,
    char: "📌",
    githubShortcode: "pushpin",
    category: "objects-other",
    description: "Pushpin",
    hasMonoVersion: true,
    hasColorVersion: true,
  },

  // === OBJECTS - TOOLS ===
  {
    code: 0x1f527,
    char: "🔧",
    githubShortcode: "wrench",
    category: "objects-tools",
    description: "Wrench",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f528,
    char: "🔨",
    githubShortcode: "hammer",
    category: "objects-tools",
    description: "Hammer",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x2699,
    char: "⚙",
    githubShortcode: "gear",
    category: "objects-tools",
    description: "Gear",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f50b,
    char: "🔋",
    githubShortcode: "battery",
    category: "objects-tech",
    description: "Battery",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4a0,
    char: "💠",
    githubShortcode: "diamond_shape_with_a_dot_inside",
    category: "symbols-shapes",
    description: "Diamond with a dot",
    hasMonoVersion: true,
    hasColorVersion: true,
  },

  // === MISC ===
  {
    code: 0x1f3ae,
    char: "🎮",
    githubShortcode: "video_game",
    category: "misc",
    description: "Video game controller",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f3b5,
    char: "🎵",
    githubShortcode: "musical_note",
    category: "misc",
    description: "Musical note",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f3b6,
    char: "🎶",
    githubShortcode: "notes",
    category: "misc",
    description: "Musical notes",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f4f7,
    char: "📷",
    githubShortcode: "camera",
    category: "objects-tech",
    description: "Camera",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x267b,
    char: "♻",
    githubShortcode: "recycle",
    category: "symbols-basic",
    description: "Recycling symbol",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x269b,
    char: "⚛",
    githubShortcode: "atom_symbol",
    category: "symbols-basic",
    description: "Atom symbol",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f6a9,
    char: "🚩",
    githubShortcode: "triangular_flag_on_post",
    category: "symbols-basic",
    description: "Triangular flag",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x2693,
    char: "⚓",
    githubShortcode: "anchor",
    category: "misc",
    description: "Anchor",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f3c6,
    char: "🏆",
    githubShortcode: "trophy",
    category: "misc",
    description: "Trophy",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
  {
    code: 0x1f451,
    char: "👑",
    githubShortcode: "crown",
    category: "misc",
    description: "Crown",
    hasMonoVersion: true,
    hasColorVersion: true,
  },
];

/**
 * Get all emoji codes that have both mono and color versions
 */
export function getMatchedEmojiCodes(): number[] {
  return EMOJI_CORE.filter((e) => e.hasMonoVersion && e.hasColorVersion).map(
    (e) => e.code
  );
}

/**
 * Get GitHub shortcode for an emoji code
 */
export function getGithubShortcode(code: number): string | undefined {
  return EMOJI_CORE.find((e) => e.code === code)?.githubShortcode;
}

/**
 * Get emoji code from GitHub shortcode
 */
export function getEmojiFromShortcode(shortcode: string): number | undefined {
  return EMOJI_CORE.find((e) => e.githubShortcode === shortcode)?.code;
}

/**
 * Get size hint for an emoji
 */
export function getSizeHint(code: number): number {
  return EMOJI_CORE.find((e) => e.code === code)?.sizeHint || 1.0;
}

/**
 * Get emojis by category
 */
export function getEmojisByCategory(category: EmojiCategory): EmojiMetadata[] {
  return EMOJI_CORE.filter((e) => e.category === category);
}

/**
 * Get all categories
 */
export function getAllCategories(): EmojiCategory[] {
  return Array.from(new Set(EMOJI_CORE.map((e) => e.category)));
}
