// @ts-nocheck
import { Processor } from "@robino/md";
import langCss from "@shikijs/langs/css";
import langDiff from "@shikijs/langs/diff";
import langHtml from "@shikijs/langs/html";
import langJson from "@shikijs/langs/json";
import langMd from "@shikijs/langs/md";
import langSql from "@shikijs/langs/sql";
import langTsx from "@shikijs/langs/tsx";
import type { MarkedExtension } from "marked";
import emojiRegex from "emoji-regex";

// GitHub-flavored markdown emoji support
// Converts :emoji: shortcodes to Unicode emoji characters
const emojiExtension: MarkedExtension = {
  extensions: [
    {
      name: "emoji",
      level: "inline",
      start(src) {
        return src.match(/:/)?.index;
      },
      tokenizer(src) {
        const match = src.match(/^:([a-z0-9_+-]+):/i);
        if (match) {
          const shortcode = match[1];
          const emoji = getEmojiFromShortcode(shortcode);
          if (emoji) {
            return {
              type: "emoji",
              raw: match[0],
              emoji,
            };
          }
        }
        return undefined;
      },
      renderer(token: any) {
        return `<span class="emoji">${token.emoji}</span>`;
      },
    },
  ],
};

// Common emoji shortcode mappings (GitHub-flavored markdown)
const emojiMap: Record<string, string> = {
  // Smileys & Emotion
  smile: "😄",
  grin: "😁",
  joy: "😂",
  heart: "❤️",
  heart_eyes: "😍",
  kissing_heart: "😘",
  relaxed: "😊",
  blush: "😊",
  wink: "😉",
  yum: "😋",
  stuck_out_tongue: "😛",
  sleeping: "😴",
  worried: "😟",
  frowning: "☹️",
  anguished: "😧",
  open_mouth: "😮",
  grimacing: "😬",
  confused: "😕",
  hushed: "😯",
  expressionless: "😑",
  unamused: "😒",
  sweat_smile: "😅",
  sweat: "😓",
  disappointed_relieved: "😥",
  weary: "😩",
  pensive: "😔",
  disappointed: "😞",
  confounded: "😖",
  fearful: "😨",
  cold_sweat: "😰",
  persevere: "😣",
  cry: "😢",
  sob: "😭",
  scream: "😱",
  angry: "😠",
  rage: "😡",
  triumph: "😤",
  sleepy: "😪",
  dizzy_face: "😵",
  mask: "😷",
  sunglasses: "😎",
  thinking: "🤔",

  // Gestures & Body Parts
  "+1": "👍",
  thumbsup: "👍",
  "-1": "👎",
  thumbsdown: "👎",
  ok_hand: "👌",
  punch: "👊",
  fist: "✊",
  wave: "👋",
  hand: "✋",
  raised_hand: "✋",
  clap: "👏",
  pray: "🙏",
  muscle: "💪",

  // Animals & Nature
  dog: "🐶",
  cat: "🐱",
  mouse: "🐭",
  hamster: "🐹",
  rabbit: "🐰",
  fox: "🦊",
  bear: "🐻",
  panda: "🐼",
  koala: "🐨",
  tiger: "🐯",
  lion: "🦁",
  cow: "🐮",
  pig: "🐷",
  frog: "🐸",
  monkey: "🐵",
  chicken: "🐔",
  penguin: "🐧",
  bird: "🐦",
  baby_chick: "🐤",
  bug: "🐛",
  bee: "🐝",
  ant: "🐜",
  snail: "🐌",
  octopus: "🐙",
  shell: "🐚",
  fish: "🐟",
  dolphin: "🐬",
  whale: "🐳",
  dragon: "🐉",
  cactus: "🌵",
  christmas_tree: "🎄",
  evergreen_tree: "🌲",
  deciduous_tree: "🌳",
  palm_tree: "🌴",
  seedling: "🌱",
  herb: "🌿",
  shamrock: "☘️",
  four_leaf_clover: "🍀",
  bamboo: "🎋",
  tanabata_tree: "🎋",
  leaves: "🍃",
  fallen_leaf: "🍂",
  maple_leaf: "🍁",
  mushroom: "🍄",
  ear_of_rice: "🌾",
  bouquet: "💐",
  tulip: "🌷",
  rose: "🌹",
  sunflower: "🌻",
  blossom: "🌼",
  cherry_blossom: "🌸",
  hibiscus: "🌺",
  earth_americas: "🌎",
  earth_africa: "🌍",
  earth_asia: "🌏",
  full_moon: "🌕",
  waning_gibbous_moon: "🌖",
  last_quarter_moon: "🌗",
  waning_crescent_moon: "🌘",
  new_moon: "🌑",
  waxing_crescent_moon: "🌒",
  first_quarter_moon: "🌓",
  waxing_gibbous_moon: "🌔",
  new_moon_with_face: "🌚",
  full_moon_with_face: "🌝",
  first_quarter_moon_with_face: "🌛",
  last_quarter_moon_with_face: "🌜",
  sun_with_face: "🌞",
  crescent_moon: "🌙",
  star: "⭐",
  star2: "🌟",
  dizzy: "💫",
  sparkles: "✨",
  comet: "☄️",
  sunny: "☀️",
  sun: "☀️",
  partly_sunny: "⛅",
  cloud: "☁️",
  zap: "⚡",
  fire: "🔥",
  boom: "💥",
  snowflake: "❄️",
  snowman: "⛄",
  rainbow: "🌈",
  ocean: "🌊",

  // Food & Drink
  coffee: "☕",
  tea: "🍵",
  sake: "🍶",
  beer: "🍺",
  beers: "🍻",
  wine_glass: "🍷",
  cocktail: "🍸",
  tropical_drink: "🍹",
  champagne: "🍾",
  apple: "🍎",
  green_apple: "🍏",
  tangerine: "🍊",
  lemon: "🍋",
  cherries: "🍒",
  grapes: "🍇",
  watermelon: "🍉",
  strawberry: "🍓",
  melon: "🍈",
  banana: "🍌",
  pineapple: "🍍",
  peach: "🍑",
  pear: "🍐",
  tomato: "🍅",
  eggplant: "🍆",
  hot_pepper: "🌶️",
  corn: "🌽",
  sweet_potato: "🍠",
  carrot: "🥕",
  bread: "🍞",
  croissant: "🥐",
  pancakes: "🥞",
  cheese: "🧀",
  meat_on_bone: "🍖",
  poultry_leg: "🍗",
  bacon: "🥓",
  hamburger: "🍔",
  fries: "🍟",
  pizza: "🍕",
  hotdog: "🌭",
  taco: "🌮",
  burrito: "🌯",
  egg: "🥚",
  fried_egg: "🍳",
  ramen: "🍜",
  stew: "🍲",
  fish_cake: "🍥",
  sushi: "🍣",
  bento: "🍱",
  curry: "🍛",
  rice_ball: "🍙",
  rice: "🍚",
  rice_cracker: "🍘",
  oden: "🍢",
  dango: "🍡",
  shaved_ice: "🍧",
  ice_cream: "🍨",
  icecream: "🍦",
  cake: "🍰",
  birthday: "🎂",
  custard: "🍮",
  candy: "🍬",
  lollipop: "🍭",
  chocolate_bar: "🍫",
  popcorn: "🍿",
  doughnut: "🍩",
  cookie: "🍪",

  // Travel & Places
  car: "🚗",
  taxi: "🚕",
  blue_car: "🚙",
  bus: "🚌",
  trolleybus: "🚎",
  train: "🚆",
  metro: "🚇",
  station: "🚉",
  tram: "🚊",
  monorail: "🚝",
  mountain_railway: "🚞",
  railway_car: "🚃",
  bullettrain_side: "🚄",
  bullettrain_front: "🚅",
  light_rail: "🚈",
  steam_locomotive: "🚂",
  bike: "🚲",
  motor_scooter: "🛵",
  motorcycle: "🏍️",
  rotating_light: "🚨",
  police_car: "🚓",
  oncoming_police_car: "🚔",
  fire_engine: "🚒",
  ambulance: "🚑",
  minibus: "🚐",
  truck: "🚚",
  articulated_lorry: "🚛",
  tractor: "🚜",
  kick_scooter: "🛴",
  airplane: "✈️",
  small_airplane: "🛩️",
  flight_departure: "🛫",
  flight_arrival: "🛬",
  rocket: "🚀",
  helicopter: "🚁",
  ship: "🚢",
  speedboat: "🚤",
  sailboat: "⛵",
  boat: "⛵",
  rowboat: "🚣",
  anchor: "⚓",
  fuelpump: "⛽",
  construction: "🚧",
  vertical_traffic_light: "🚦",
  traffic_light: "🚥",
  checkered_flag: "🏁",
  tent: "⛺",
  rainbow_flag: "🏳️‍🌈",
  pirate_flag: "🏴‍☠️",
  flag_us: "🇺🇸",
  flag_gb: "🇬🇧",
  flag_fr: "🇫🇷",
  flag_de: "🇩🇪",
  flag_jp: "🇯🇵",
  flag_kr: "🇰🇷",
  flag_cn: "🇨🇳",
  flag_ru: "🇷🇺",

  // Activities
  soccer: "⚽",
  baseball: "⚾",
  basketball: "🏀",
  volleyball: "🏐",
  football: "🏈",
  rugby_football: "🏉",
  tennis: "🎾",
  "8ball": "🎱",
  bowling: "🎳",
  golf: "⛳",
  mountain_bicyclist: "🚵",
  bicyclist: "🚴",
  horse_racing: "🏇",
  snowboarder: "🏂",
  swimmer: "🏊",
  surfer: "🏄",
  ski: "🎿",
  fishing_pole_and_fish: "🎣",
  running_shirt_with_sash: "🎽",
  trophy: "🏆",
  medal_sports: "🏅",
  medal_military: "🎖️",
  "1st_place_medal": "🥇",
  "2nd_place_medal": "🥈",
  "3rd_place_medal": "🥉",
  dart: "🎯",
  video_game: "🎮",
  space_invader: "👾",
  game_die: "🎲",
  slot_machine: "🎰",

  // Objects
  watch: "⌚",
  iphone: "📱",
  calling: "📲",
  computer: "💻",
  keyboard: "⌨️",
  desktop_computer: "🖥️",
  printer: "🖨️",
  computer_mouse: "🖱️",
  trackball: "🖲️",
  joystick: "🕹️",
  clamp: "🗜️",
  minidisc: "💽",
  floppy_disk: "💾",
  cd: "💿",
  dvd: "📀",
  vhs: "📼",
  camera: "📷",
  camera_flash: "📸",
  video_camera: "📹",
  movie_camera: "🎥",
  film_projector: "📽️",
  film_strip: "🎞️",
  telephone_receiver: "📞",
  phone: "☎️",
  pager: "📟",
  fax: "📠",
  tv: "📺",
  radio: "📻",
  microphone: "🎤",
  studio_microphone: "🎙️",
  level_slider: "🎚️",
  control_knobs: "🎛️",
  stopwatch: "⏱️",
  timer_clock: "⏲️",
  alarm_clock: "⏰",
  hourglass_flowing_sand: "⏳",
  hourglass: "⌛",
  satellite: "📡",
  battery: "🔋",
  electric_plug: "🔌",
  bulb: "💡",
  flashlight: "🔦",
  candle: "🕯️",
  fire_extinguisher: "🧯",
  wrench: "🔧",
  hammer: "🔨",
  hammer_and_pick: "⚒️",
  hammer_and_wrench: "🛠️",
  pick: "⛏️",
  nut_and_bolt: "🔩",
  gear: "⚙️",
  chains: "⛓️",
  gun: "🔫",
  bomb: "💣",
  hocho: "🔪",
  dagger: "🗡️",
  crossed_swords: "⚔️",
  shield: "🛡️",
  mag: "🔍",
  mag_right: "🔎",
  lock: "🔒",
  unlock: "🔓",
  lock_with_ink_pen: "🔏",
  closed_lock_with_key: "🔐",
  key: "🔑",
  old_key: "🗝️",

  // Symbols
  "100": "💯",
  "1234": "🔢",
  hash: "#️⃣",
  asterisk: "*️⃣",
  zero: "0️⃣",
  one: "1️⃣",
  two: "2️⃣",
  three: "3️⃣",
  four: "4️⃣",
  five: "5️⃣",
  six: "6️⃣",
  seven: "7️⃣",
  eight: "8️⃣",
  nine: "9️⃣",
  keycap_ten: "🔟",
  white_check_mark: "✅",
  heavy_check_mark: "✔️",
  ballot_box_with_check: "☑️",
  x: "❌",
  negative_squared_cross_mark: "❎",
  heavy_plus_sign: "➕",
  heavy_minus_sign: "➖",
  heavy_division_sign: "➗",
  heavy_multiplication_x: "✖️",
  infinity: "♾️",
  question: "❓",
  grey_question: "❔",
  grey_exclamation: "❕",
  exclamation: "❗",
  wavy_dash: "〰️",
  copyright: "©️",
  registered: "®️",
  tm: "™️",
  currency_exchange: "💱",
  dollar: "💵",
  yen: "💴",
  euro: "💶",
  pound: "💷",
  moneybag: "💰",
  money_with_wings: "💸",
  credit_card: "💳",
  chart: "💹",
  email: "📧",
  "e-mail": "📧",
  incoming_envelope: "📨",
  envelope_with_arrow: "📩",
  outbox_tray: "📤",
  inbox_tray: "📥",
  package: "📦",
  mailbox: "📫",
  mailbox_closed: "📪",
  mailbox_with_mail: "📬",
  mailbox_with_no_mail: "📭",
  postbox: "📮",
  ballot_box: "🗳️",
  pencil2: "✏️",
  pencil: "📝",
  memo: "📝",
  briefcase: "💼",
  file_folder: "📁",
  open_file_folder: "📂",
  card_index_dividers: "🗂️",
  date: "📅",
  calendar: "📆",
  spiral_notepad: "🗒️",
  spiral_calendar: "🗓️",
  card_index: "📇",
  chart_with_upwards_trend: "📈",
  chart_with_downwards_trend: "📉",
  bar_chart: "📊",
  clipboard: "📋",
  pushpin: "📌",
  round_pushpin: "📍",
  paperclip: "📎",
  paperclips: "🖇️",
  straight_ruler: "📏",
  triangular_ruler: "📐",
  scissors: "✂️",
  card_file_box: "🗃️",
  file_cabinet: "🗄️",
  wastebasket: "🗑️",
  link: "🔗",
  bookmark: "🔖",
  bookmark_tabs: "📑",
  ledger: "📒",
  notebook: "📓",
  notebook_with_decorative_cover: "📔",
  closed_book: "📕",
  green_book: "📗",
  blue_book: "📘",
  orange_book: "📙",
  books: "📚",
  book: "📖",
  microscope: "🔬",
  telescope: "🔭",
  newspaper: "📰",
  art: "🎨",
  paintbrush: "🖌️",
  crayon: "🖍️",
  fountain_pen: "🖊️",
  pen: "🖊️",
  black_nib: "✒️",

  // Flags & Symbols
  triangular_flag_on_post: "🚩",
  crossed_flags: "🎌",
  black_flag: "🏴",
  white_flag: "🏳️",

  // Arrows
  arrow_left: "←",
  arrow_right: "→",
  arrow_up: "↑",
  arrow_down: "↓",
  arrow_upper_left: "↖️",
  arrow_upper_right: "↗️",
  arrow_lower_right: "↘️",
  arrow_lower_left: "↙️",
  left_right_arrow: "↔️",
  arrow_up_down: "↕️",
  arrows_counterclockwise: "🔄",
  arrow_backward: "◀️",
  arrow_forward: "▶️",
  arrow_up_small: "🔼",
  arrow_down_small: "🔽",
  leftwards_arrow_with_hook: "↩️",
  arrow_right_hook: "↪️",
  information_source: "ℹ️",
  rewind: "⏪",
  fast_forward: "⏩",
  arrow_double_up: "⏫",
  arrow_double_down: "⏬",
  arrow_heading_up: "⤴️",
  arrow_heading_down: "⤵️",
};

function getEmojiFromShortcode(shortcode: string): string | null {
  return emojiMap[shortcode.toLowerCase()] || null;
}

export const processor = new Processor({
  anchor: false,
  highlighter: {
    langs: [langCss, langHtml, langTsx, langDiff, langJson, langSql, langMd],
    langAlias: {
      js: "tsx",
      ts: "tsx",
      jsx: "tsx",
      mdx: "md",
      svelte: "html",
      astro: "html",
    },
  },
  marked: {
    extensions: [emojiExtension],
  },
});
